# Generated by Django 6.0 on 2026-01-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='solary',
            new_name='salary',
        ),
    ]
